<?php
/**
 * Oblique Pro Theme Customizer
 *
 * @package Oblique
 */

/**
 * Customize Register
 *
 * @param $wp_customize
 */
function oblique_pro_customize_register( $wp_customize ) {

	// ___Pro options___//
	$wp_customize->add_panel(
		'oblique_pro_panel', array(
			'priority'       => 39,
			'capability'     => 'edit_theme_options',
			'theme_supports' => '',
			'title'          => __( 'Oblique Pro options', 'oblique' ),
		)
	);
	// ___Footer___//
	$wp_customize->add_section(
		'oblique_footer_pro',
		array(
			'title'    => __( 'Footer credits', 'oblique' ),
			'priority' => 10,
			'panel'    => 'oblique_pro_panel',
		)
	);
	$wp_customize->add_setting(
		'footer_credits',
		array(
			'default'           => '',
			'sanitize_callback' => 'oblique_sanitize_text',
		)
	);
	$wp_customize->add_control(
		'footer_credits',
		array(
			'label'    => __( 'Custom footer credits *HTML allowed*', 'oblique' ),
			'section'  => 'oblique_footer_pro',
			'type'     => 'text',
			'priority' => 10,
		)
	);

	// ___Below header widget area___//
	$wp_customize->add_section(
		'oblique_extra_widget_area',
		array(
			'title'       => __( 'Extra widget area', 'oblique' ),
			'priority'    => 15,
			'panel'       => 'oblique_pro_panel',
			'description' => __( 'Activate your extra widget area here then go to Appearance > Widgets to add widgets in it.', 'oblique' ),
		)
	);
	// Activate
	$wp_customize->add_setting(
		'activate_bh_widgets',
		array(
			'sanitize_callback' => 'oblique_sanitize_checkbox',
		)
	);
	$wp_customize->add_control(
		'activate_bh_widgets',
		array(
			'type'     => 'checkbox',
			'label'    => __( 'Activate the extra widget area?', 'oblique' ),
			'section'  => 'oblique_extra_widget_area',
			'priority' => 10,
		)
	);
	// Center
	$wp_customize->add_setting(
		'center_bh_widgets',
		array(
			'sanitize_callback' => 'oblique_sanitize_checkbox',
		)
	);
	$wp_customize->add_control(
		'center_bh_widgets',
		array(
			'type'     => 'checkbox',
			'label'    => __( 'Center the content? (depends on the widgets)', 'oblique' ),
			'section'  => 'oblique_extra_widget_area',
			'priority' => 11,
		)
	);
	// Background color
	$wp_customize->add_setting(
		'bg_bh_widgets',
		array(
			'default'           => '#ffffff',
			'sanitize_callback' => 'sanitize_hex_color',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'bg_bh_widgets',
			array(
				'label'    => __( 'Background color', 'oblique' ),
				'section'  => 'oblique_extra_widget_area',
				'priority' => 12,
			)
		)
	);
	// Color
	$wp_customize->add_setting(
		'color_bh_widgets',
		array(
			'default'           => '#50545C',
			'sanitize_callback' => 'sanitize_hex_color',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'color_bh_widgets',
			array(
				'label'    => __( 'Color', 'oblique' ),
				'section'  => 'oblique_extra_widget_area',
				'priority' => 13,
			)
		)
	);

	// ___Slider___//
	$wp_customize->add_section(
		'oblique_pro_slider',
		array(
			'title'       => __( 'Slider', 'oblique' ),
			'priority'    => 15,
			'panel'       => 'oblique_pro_panel',
			'description' => __( 'This section lets you add a shortcode for a slider to replace the header image.', 'oblique' ),
		)
	);
	// Activate
	$wp_customize->add_setting(
		'show_slider',
		array(
			'sanitize_callback' => 'oblique_sanitize_checkbox',
		)
	);
	$wp_customize->add_control(
		'show_slider',
		array(
			'type'     => 'checkbox',
			'label'    => __( 'Activate the slider?', 'oblique' ),
			'section'  => 'oblique_pro_slider',
			'priority' => 10,
		)
	);
	$wp_customize->add_setting(
		'slider_shortcode',
		array(
			'default'           => '',
			'sanitize_callback' => 'oblique_sanitize_text',
		)
	);

	$oblique_nivo_shortcode_desc = __( '. We recommend the Nivo Slider plugin.', 'oblique' );

	if ( ! class_exists( 'WordPress_Nivo_Slider_Lite' ) ) {
		/* translators: Nivo Slider plugin */
		$oblique_nivo_shortcode_desc = sprintf( __( '. We recommend the %s plugin.', 'oblique' ), sprintf( '<a href="' . esc_url( wp_nonce_url( self_admin_url( 'update.php?action=install-plugin&plugin=nivo-slider-lite' ), 'install-plugin_nivo-slider-lite' ) ) . '" >%s</a>', 'Nivo Slider' ) );
	}

	$wp_customize->add_control(
		'slider_shortcode',
		array(
			'label'       => __( 'Slider shortcode', 'oblique' ),
			'description' => __( 'Add here the shortcode generated by your slider plugin', 'oblique' ) . $oblique_nivo_shortcode_desc,
			'section'     => 'oblique_pro_slider',
			'type'        => 'text',
			'priority'    => 10,
		)
	);

	// ___Extra colors___//
	$wp_customize->add_section(
		'oblique_extra_colors',
		array(
			'title'    => __( 'Extra colors', 'oblique' ),
			'priority' => 19,
			'panel'    => 'oblique_pro_panel',
		)
	);

	// Social Icons
	$wp_customize->add_setting(
		'social_icons_color',
		array(
			'default'           => '#ffffff',
			'sanitize_callback' => 'sanitize_hex_color',
			'transport'         => 'postMessage',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'social_icons_color',
			array(
				'label'    => __( 'Social Icons', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 10,
			)
		)
	);
	// Social Icons Hover
	$wp_customize->add_setting(
		'social_icons_hover',
		array(
			'default'           => '#23b6b6',
			'sanitize_callback' => 'sanitize_hex_color',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'social_icons_hover',
			array(
				'label'    => __( 'Social Icons Hover', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 11,
			)
		)
	);
	// Widget bg
	$wp_customize->add_setting(
		'widgets_background',
		array(
			'default'           => '#17191B',
			'sanitize_callback' => 'sanitize_hex_color',
			'transport'         => 'postMessage',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'widgets_background',
			array(
				'label'    => __( 'Widgets background', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 12,
			)
		)
	);
	// Widget color
	$wp_customize->add_setting(
		'widgets_color',
		array(
			'default'           => '#ffffff',
			'sanitize_callback' => 'sanitize_hex_color',
			'transport'         => 'postMessage',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'widgets_color',
			array(
				'label'    => __( 'Widgets color', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 13,
			)
		)
	);
	// Footer menu
	$wp_customize->add_setting(
		'footer_menu_color',
		array(
			'default'           => '#8b8b8b',
			'sanitize_callback' => 'sanitize_hex_color',
			'transport'         => 'postMessage',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'footer_menu_color',
			array(
				'label'    => __( 'Footer Menu', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 14,
			)
		)
	);
	// Footer menu hover
	$wp_customize->add_setting(
		'footer_menu_hover',
		array(
			'default'           => '#9FA7AF',
			'sanitize_callback' => 'sanitize_hex_color',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'footer_menu_hover',
			array(
				'label'    => __( 'Footer Menu Hover', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 15,
			)
		)
	);
	// Article titles
	$wp_customize->add_setting(
		'entry_title_color',
		array(
			'default'           => '#2B2D3A',
			'sanitize_callback' => 'sanitize_hex_color',
			'transport'         => 'postMessage',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'entry_title_color',
			array(
				'label'    => __( 'Article Title', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 16,
			)
		)
	);
	// Article titles hover
	$wp_customize->add_setting(
		'entry_title_hover',
		array(
			'default'           => '#23b6b6',
			'sanitize_callback' => 'sanitize_hex_color',
		)
	);
	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'entry_title_hover',
			array(
				'label'    => __( 'Article Title Hover', 'oblique' ),
				'section'  => 'oblique_extra_colors',
				'priority' => 17,
			)
		)
	);

	// ___Typography___//
	$wp_customize->add_section(
		'oblique_typography',
		array(
			'title'    => __( 'Typography', 'oblique' ),
			'priority' => 18,
			'panel'    => 'oblique_pro_panel',
		)
	);

	$weights = array(
		'300' => '300',
		'400' => '400',
		'500' => '500',
		'600' => '600',
		'700' => '700',
		'800' => '800',
	);

	$wp_customize->add_setting(
		'body_font_weight',
		array(
			'sanitize_callback' => 'oblique_sanitize_select',
			'default'           => '400',
		)
	);
	$wp_customize->add_control(
		'body_font_weight',
		array(
			'type'        => 'select',
			'label'       => __( 'Body text font weight', 'oblique' ),
			'section'     => 'oblique_typography',
			'description' => __( 'Font weight availability depends on the font you are using', 'oblique' ),
			'priority'    => 10,
			'choices'     => $weights,
		)
	);
	$wp_customize->add_setting(
		'headings_font_weight',
		array(
			'sanitize_callback' => 'oblique_sanitize_select',
			'default'           => '500',
		)
	);
	$wp_customize->add_control(
		'headings_font_weight',
		array(
			'type'        => 'select',
			'label'       => __( 'Headings font weight', 'oblique' ),
			'section'     => 'oblique_typography',
			'description' => __( 'Font weight availability depends on the font you are using', 'oblique' ),
			'priority'    => 10,
			'choices'     => $weights,
		)
	);

	$wp_customize->add_setting(
		'body_line_height',
		array(
			'default'           => '1.55',
			'sanitize_callback' => 'oblique_sanitize_text',
		)
	);
	$wp_customize->add_control(
		'body_line_height',
		array(
			'label'       => __( 'Body line height', 'oblique' ),
			'section'     => 'oblique_typography',
			'type'        => 'number',
			'priority'    => 10,
			'input_attrs' => array(
				'min'  => 1,
				'max'  => 3,
				'step' => 0.05,
			),
		)
	);
	$wp_customize->add_setting(
		'headings_line_height',
		array(
			'default'           => '1.1',
			'sanitize_callback' => 'oblique_sanitize_text',
		)
	);
	$wp_customize->add_control(
		'headings_line_height',
		array(
			'label'       => __( 'Headings line height', 'oblique' ),
			'section'     => 'oblique_typography',
			'type'        => 'number',
			'priority'    => 10,
			'input_attrs' => array(
				'min'  => 1,
				'max'  => 3,
				'step' => 0.05,
			),
		)
	);
	$wp_customize->add_setting(
		'body_letter_spacing',
		array(
			'default'           => '0',
			'sanitize_callback' => 'oblique_sanitize_text',
		)
	);
	$wp_customize->add_control(
		'body_letter_spacing',
		array(
			'label'       => __( 'Body letter spacing [px]', 'oblique' ),
			'section'     => 'oblique_typography',
			'type'        => 'number',
			'priority'    => 10,
			'input_attrs' => array(
				'min'  => 0,
				'max'  => 5,
				'step' => 0.5,
			),
		)
	);
	$wp_customize->add_setting(
		'headings_letter_spacing',
		array(
			'default'           => '0',
			'sanitize_callback' => 'oblique_sanitize_text',
		)
	);
	$wp_customize->add_control(
		'headings_letter_spacing',
		array(
			'label'       => __( 'Headings letter spacing [px]', 'oblique' ),
			'section'     => 'oblique_typography',
			'type'        => 'number',
			'priority'    => 10,
			'input_attrs' => array(
				'min'  => 0,
				'max'  => 5,
				'step' => 0.5,
			),
		)
	);
	// ___Layout___//
	$wp_customize->add_section(
		'oblique_alternative_layout',
		array(
			'title'       => __( 'Alternative layout', 'oblique' ),
			'priority'    => 15,
			'panel'       => 'oblique_pro_panel',
			'description' => __( 'Here you can activate the alternative homepage layout.', 'oblique' ),
		)
	);
	// Activate
	$wp_customize->add_setting(
		'oblique_alt_layout',
		array(
			'sanitize_callback' => 'oblique_sanitize_checkbox',
		)
	);
	$wp_customize->add_control(
		'oblique_alt_layout',
		array(
			'type'     => 'checkbox',
			'label'    => __( 'Activate the alternative layout?', 'oblique' ),
			'section'  => 'oblique_alternative_layout',
			'priority' => 10,
		)
	);

}
add_action( 'customize_register', 'oblique_pro_customize_register' );

/**
 * Sanitize select.
 *
 * @param $input
 *
 * @return mixed
 */
function oblique_sanitize_select( $input ) {
	if ( in_array(
		$input, array(
			'300' => '300',
			'400' => '400',
			'500' => '500',
			'600' => '600',
			'700' => '700',
			'800' => '800',
		), true
	) ) {
		return $input;
	}
}
